development:
  secret_key_base: super_long_secret_key_for_development
  google_client_id: 267026120889-4d8q4kiaen2i7fnd194b4gh7aool29is.apps.googleusercontent.com
  google_client_secret: Us5-QcgapK2CUpyT-w9RSTF0
